#!/usr/bin/env bash

# Terminal
alias ls="ls -la"
alias sbash="source ~/.bash_profile"
alias path="echo $PATH | tr ':' '\n'"
alias airport="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"

# Applications
alias mate="open -a ~/Applications/Sublime\ Text\ 2.app"
alias code="open -a /Applications/Visual\ Studio\ Code.app"

# Git
alias gs="git status"
alias gl="git log --pretty=format:'%h %C(red)%ad %C(yellow)%an%Cgreen%d %Creset%s'"
alias gd="git diff"
alias gdd="git difftool"
alias gds="git diff --staged"
alias gdds="git difftool --staged"
alias gpr="git pull --rebase"
alias gst="git stash"
alias gstl="git stash list"
alias gstp="git stash pop"
alias gpush='git push origin master'
alias gpull='git pull origin master'

# Rails
alias be="bundle exec"
