#!/usr/bin/env bash

# Meta
alias showalias="less ~/.dotfiles/aliases"

# Terminal
alias ls="ls -la"
alias sbash="source ~/.bash_profile"
alias path="echo $PATH | tr ':' '\n'"
alias airport="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"

# Applications
alias mate2="open -a ~/Applications/Sublime\ Text\ 2.app"
alias mate="open -a /Applications/Sublime\ Text.app"
alias code="open -a /Applications/Visual\ Studio\ Code.app"
alias atom="open -a /Applications/Atom.app"

# Git
alias gs="git status"
alias gl="git log --pretty=format:'%h %C(red)%ad %C(yellow)%an%Cgreen%d %Creset%s'"
alias gd="git diff --word-diff"
alias gdd="git difftool"
alias gds="git diff --staged --word-diff"
alias gdds="git difftool --staged"
alias gpr="git pull --rebase"
alias gst="git stash"
alias gstl="git stash list"
alias gstp="git stash pop"
alias gpush='git push origin master'
alias gpull='git pull origin master'

syncfork () {
  num=${1:-5}
  dmesg |grep -iw usb|tail -$num
}
alias syncfork='git fetch upstream; git checkout master; git merge upstream/master'

# Git enhancements from https://github.com/csswizardry/csswizardry.github.com/issues/66
alias recap='git log --all --oneline --no-merges --author=jonfriskics@gmail.com'
alias gt="git tag -l --sort=v:refname | tail -n8"
alias gsub="grep path .gitmodules | sed 's/.*= //'"

# Rails
alias be="bundle exec"
alias rbload='eval "$(rbenv init -)"'

# NPM
alias modules='npm ls --depth=0'
alias gmodules='npm -g ls --depth=0'
alias loadnvm=". $HOME/.nvm/nvm.sh"

# Quicktime
alias playslow="osascript -e 'tell application \"QuickTime Player\" to set rate of document 1 to 0.5'"

# Network Stuff
alias ports="sudo lsof -PiTCP -sTCP:LISTEN"
alias portsall="lsof -Pn -i4"