#!/usr/bin/env bash

export DOTFILES_PATH=~/.dotfiles
source $DOTFILES_PATH/aliases
source $DOTFILES_PATH/colors

if [ ! -e "env" ] ; then
    touch "env"
fi

source $DOTFILES_PATH/env
source $DOTFILES_PATH/nvm
source $DOTFILES_PATH/osx_prefs
source $DOTFILES_PATH/path
source $DOTFILES_PATH/powerline
source $DOTFILES_PATH/rbenv

if [ ! -e "$DOTFILES_PATH/../.gitignore" ] ; then
  source $DOTFILES_PATH/symlinks
fi

if [ ! -e "$DOTFILES_PATH/../.gitconfig" ] ; then
  source $DOTFILES_PATH/symlinks
fi