#!/usr/bin/env bash

export DOTFILES_PATH=~/.dotfiles
source $DOTFILES_PATH/aliases
source $DOTFILES_PATH/colors

if [ ! -e "$DOTFILES_PATH/env" ] ; then
    touch "env"
fi

source $DOTFILES_PATH/env

if [ ! -e "$DOTFILES_PATH/../.gitconfig" ] ; then
  ln -s $DOTFILES_PATH/gitconfig ~/.gitconfig
fi

if [ ! -e "$DOTFILES_PATH/../.gitignore" ] ; then
  ln -s $DOTFILES_PATH/gitignore ~/.gitignore
fi

source $DOTFILES_PATH/nvm
source $DOTFILES_PATH/osx_prefs
source $DOTFILES_PATH/path
source $DOTFILES_PATH/powerline
source $DOTFILES_PATH/rbenv
source $DOTFILES_PATH/z
