#!/usr/bin/env bash

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew doctor
brew install git
brew install hub
brew install nvm
brew install openssl
brew install postgresql
brew install python
brew install rbenv
brew install redis
brew install z