#!/usr/bin/env bash

gem install bundler
gem install rails

# Installing Puma on El Capitan
# Leaving this in here as a reference since I know I'll need it again
# gem install puma -v '2.8.2' -- --with-cppflags=-I/usr/local/opt/openssl/include --with-ldflags=-L/usr/local/opt/openssl/lib

# This might do the trick too though!
bundle config build.puma --with-opt-dir=/usr/local/opt/openssl
