#!/usr/bin/env bash

gem install bundler
gem install rails
gem install fastlane

# Installing Puma on El Capitan
# Leaving this in here as a reference since I know I'll need it again
# gem install puma -v '2.8.2' -- --with-cppflags=-I/usr/local/opt/openssl/include --with-ldflags=-L/usr/local/opt/openssl/lib

# This might do the trick too though!
bundle config build.puma --with-opt-dir=/usr/local/opt/openssl
bundle config build.eventmachine --with-opt-dir=/usr/local/opt/openssl

# Installing libv8 and therubyracer on Sierra
# gem install libv8 -v '3.16.14.13' -- --with-system-v8
# gem install therubyracer -- --with-v8-dir=/usr/local/opt/v8-315

# Installing old pg
# sudo env ARCHFLAGS="-arch x86_64" gem install pg -v '0.17.1' -- --with-pg-config=/usr/local/Cellar/postgresql/10.5/bin/pg_config