#!/usr/bin/env bash

git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`

. ~/.nvm/nvm.sh

nvm install 4.2.4

nvm alias default 4.2.4

nvm use default